# Generated by Django 2.1.7 on 2019-03-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='black_list',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='ブラックリスト'),
        ),
    ]
