# Generated by Django 2.1.7 on 2019-03-13 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='article',
        ),
    ]
