# Generated by Django 2.1.7 on 2019-03-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190313_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
