# Generated by Django 2.2 on 2019-04-07 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_blacklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlackList',
        ),
    ]
